name: Reddit Bot

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install dependencies
        run: pip install requests googletrans==4.0.0-rc1 pillow

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python main.py
